version: '3.8'

services:
  app:
    image: levelup0210/levelup:latest
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      - SPRING_ELASTICSEARCH_USERNAME=elastic
      - SPRING_ELASTICSEARCH_PASSWORD=your-secure-password
    ports:
      - "8080:8080"
    networks:
      - app-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=your-secure-password
      - xpack.security.authc.api_key.enabled=true
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=j*DqotOY_x+x0aD2H36h
    ports:
      - "5601:5601"
    networks:
      - app-network
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: .
      dockerfile: logstash.Dockerfile
    container_name: logstash
    depends_on:
      - elasticsearch
    networks:
      - app-network
    environment:
      - XPACK_MONITORING_ENABLED=true
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_MONITORING_ELASTICSEARCH_USERNAME=elastic
      - XPACK_MONITORING_ELASTICSEARCH_PASSWORD=your-secure-password
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
    driver: local
  elasticsearch-data:
    driver: local
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge
