input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/mysql-connector-java.jar"
    jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
    jdbc_connection_string => "jdbc:mysql://host.docker.internal:3306/levelup"
    jdbc_user => "root"
    jdbc_password => "0515"
    schedule => "*/30 * * * *"
    statement => "SELECT * FROM review WHERE is_deleted = false"
    type => "review"
  }

  tcp {
    port => 5044
    codec => json_lines
    type => "log"
  }
}

filter {
  mutate {
    convert => { "id" => "string" }
  }

  ruby {
    code => "
      require 'time'
      event.set('timestamp_kst', event.get('@timestamp').time.localtime('+09:00').strftime('%Y-%m-%d %H:%M:%S')) if event.get('@timestamp')
      event.set('updated_at_kst', event.get('updated_at').time.localtime('+09:00').strftime('%Y-%m-%d %H:%M:%S')) if event.get('updated_at')
      event.set('created_at_kst', event.get('created_at').time.localtime('+09:00').strftime('%Y-%m-%d %H:%M:%S')) if event.get('created_at')
    "
  }

  # 액세스 로그를 위한 처리
  if [type] == "log" {
    # timestamp_kst를 기반으로 document_id 설정
    mutate {
      add_field => { "document_id" => "%{timestamp_kst}" }
    }
  }

  json {
      source => "message"
  }
}

output {
  if [type] == "review" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      user => "elastic"
      password => "your-secure-password"
      index => "review"  # 기존 "review"를 alias로 변경
      document_id => "%{id}"
    }
  }

  if [type] == "log" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      user => "elastic"
      password => "your-secure-password"
      index => "application-logs"  # alias 기반 저장
      document_id => "%{document_id}"
    }
  }
}

