input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/mysql-connector-java.jar"
    jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
    jdbc_connection_string => "jdbc:mysql://host.docker.internal:3306/levelup"
    jdbc_user => "root"
    jdbc_password => "0515"
    schedule => "*/30 * * * *"
    statement => "SELECT * FROM review WHERE is_deleted = false"
  }
}

filter {
  mutate {
    convert => { "id" => "string" }
  }
}

output {
  if [type] == "review" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      user => "elastic"
      password => "your-secure-password"
      index => "review"  # 기존 "review"를 alias로 변경
      document_id => "%{id}"
    }
  }

  if [type] == "log" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      user => "elastic"
      password => "your-secure-password"
      index => "application-logs"  # alias 기반 저장
      document_id => "%{document_id}"
    }
  }
}

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "elastic"
    password => "your-secure-password"
    ssl => false
    index => "review"  # 인덱스 이름을 review로 설정
    document_id => "%{id}"
  }
}
