input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/mysql-connector-java.jar"
    jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
    jdbc_connection_string => "jdbc:mysql://host.docker.internal:3306/levelup"
    jdbc_user => "root"
    jdbc_password => "0515"
    schedule => "*/30 * * * *"
    statement => "SELECT * FROM review WHERE is_deleted IS NULL OR is_deleted = false"
    type => "review"
    target => "ecs_review"
  }

  tcp {
    port => 5044
    codec => json_lines { target => "ecs_log" }
    type => "log"
  }
}

filter {
  mutate {
    convert => { "id" => "string" }
  }

  ruby {
    code => "
      require 'time'
      event.set('timestamp_kst', event.get('@timestamp').time.localtime('+09:00').strftime('%Y-%m-%d %H:%M:%S')) if event.get('@timestamp')
      event.set('updated_at_kst', event.get('updated_at').time.localtime('+09:00').strftime('%Y-%m-%d %H:%M:%S')) if event.get('updated_at')
      event.set('created_at_kst', event.get('created_at').time.localtime('+09:00').strftime('%Y-%m-%d %H:%M:%S')) if event.get('created_at')
    "
  }

  if [type] == "log" {
    mutate {
      add_field => { "document_id" => "%{timestamp_kst}-%{host}-%{uuid}" }
    }
  }

  if [message] =~ "^\{.*\}$" {
    json {
      source => "message"
      target => "ecs_message"
    }
  }
}

output {
  if [type] == "review" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      user => "elastic"
      password => "your-secure-password"
      ssl_enabled => false
      index => "review"
      document_id => "%{id}"
    }
  }

  if [type] == "log" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      user => "elastic"
      password => "your-secure-password"
      ssl_enabled => false
      index => "application-logs"
      document_id => "%{document_id}"
    }
  }
}
