spring:
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URI:http://elasticsearch:9200}
    username: ${SPRING_ELASTICSEARCH_USERNAME:elastic}
    password: ${SPRING_ELASTICSEARCH_PASSWORD:your-secure-password}
  datasource:
    url: jdbc:mysql://db-mysql.ctw4cseqk9v4.ap-northeast-2.rds.amazonaws.com:3306/levelup
    username: admin
    password: levelup0210
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: mongodb+srv://levelup:ZsM2V6brfRdizhx6@cluster0.5rnlx.mongodb.net/levelup?retryWrites=true&w=majority&appName=Cluster0&tls=true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1060049658038-orbts050f98ms7qo056j83u1rcbmpncq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-id: LWDBysjh__U_UIbItKoo
            client-secret: 9H71Iz_CTS
            scope:
              - name,nickname,email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

management:
  endpoints:
    web:
      exposure:
        include: "*"


jwt:
  secret:
    key: NDkxOWJkYzRmNTU3N2RjMGMyZDFlZmM5NDMxODk3ZTUxYjdkZDNkOGZmNzU2YTJiMmQ0ZmNlNzVmYzE1MTRhZA==
